### ISSUE TITLE
Notification Style

### ISSUE THREAD

**Issue by nournia** [sadra/middle-east#1]
Hi,
Thank you for sharing this great theme.
It seems that notification messages need some styling to look properly.
For checking this issue you can activate Focus Mode (View menu) to see how messages are styled.

**Comment by sadra** [comment]
Thank for the report, that fixed at #fe0b9b9 .
Please download the latest version.

**Comment by sadra** [comment]
Fixes #fe0b9b9

**Comment by sadra** [comment]
Thank's for report the issue, please download latest version: [Releases](https://github.com/sadra/middle-east/releases/latest)
