### ISSUE TITLE
PDF Print Style

### ISSUE THREAD

**Issue by nournia** [sadra/middle-east#2]
Hi,
I think you can revise how PDF export would print markdown document using `middle-east` theme. For example, I don't see any point in printing `H1` heading tag. Adding some sytles for print mode may help, like this:

     @media print {
          // ...
     }

**Comment by sadra** [comment]
Thank's for report the issue, please download latest version: [Releases](https://github.com/sadra/middle-east/releases/latest)

**Comment by nournia** [comment]
Thanks a lot.
