### ISSUE TITLE
How to switch RTL to LTR?

### ISSUE THREAD

**Issue by mvxim** [sadra/middle-east#3]
Your theme really awesome and infusing some Bear's style into Typora, I like it. But any text I type is RTL, and I can't find some option to switch it to LTR. Can you kindly help me find out how to do it?

**Comment by vctcn93** [comment]
> Your theme really awesome and infusing some Bear's style into Typora, I like it. But any text I type is RTL, and I can't find some option to switch it to LTR. Can you kindly help me find out how to do it?

open _middle-east-night.css_ in theme folder, search **rtl** and change them to **ltr**.

**Comment by sadra** [comment]
> Your theme really awesome and infusing some Bear's style into Typora, I like it. But any text I type is RTL, and I can't find some option to switch it to LTR. Can you kindly help me find out how to do it?

As @vctcn93 mentioned, you can edit the `middle-east-night.css` file to make it RTL,
or use the [Ursine](https://theme.typora.io/theme/Ursine/) theme; That looks like to the bear editor too.
