### ISSUE TITLE
RTL in code

### ISSUE THREAD

**Issue by a-Rahmati** [sadra/middle-east#8]
Hello,
In this theme, code is displayed RTL too when it's in a list. but it should be LTR.
Is there any way to fix it?

![Selection_097](https://user-images.githubusercontent.com/52320192/124351837-e2a5bf00-dc11-11eb-9f6e-03d68e00dbdf.png)
[file above.md](https://github.com/sadra/middle-east/files/6758258/RTL.problem.md)

**Comment by seenpeh** [comment]
How to Write LTR in this theme? I want it for English Contexts in the middle of persian.

**Comment by a-Rahmati** [comment]
@seenpeh You can add HTML code to change the direction.
```
<div style="direction: ltr">
some English text
</div>
```

**Comment by a-Rahmati** [comment]
Seems the issue is solved.
